### ISSUE TITLE
Server errors

### ISSUE THREAD

**Issue by CamBanfield** [tonyjbutler/moodle-mod_nln#2]
Hi,

When accessing the "Browse the NLN materials..." page from within the NLN course resource I'm getting the following error:
"405 - HTTP verb used to access this page is not allowed.
The page you are looking for cannot be displayed because an invalid method (HTTP verb) was used to attempt access."

When visiting the URL manually "http://noodle.nln.ac.uk/noodle.asp?act=Start" I'm then greeted by a message starting with "The Noodle browser has now closed.". 

Do you have any plan to maintain this plugin or is this end of life now?

Thanks,

**Comment by tonyjbutler** [comment]
Hi Cam,

Thanks for bringing this to my attention. Unfortunately I only maintain the Moodle 2.x port of the plugin and have no relationship with Xtensis who developed (and then abandoned) the original 'Noodle' plugin for Moodle 1.9. Hence I have no control over the way Xtensis host the NLN resources, which sadly now seems to have changed in a way that renders this plugin largely inoperable.

I'll continue to maintain the plugin for Moodle 2.9, as resources that have already been added still seem to work fine, and I'll modify the config form to display a message that the NLN materials can no longer be added in this way. This should give people enough time to migrate to using the new Xtensis service for adding such resources to Moodle, described at http://xtlearn.net/Help/NLN.

Thanks,
Tony

**Comment by tonyjbutler** [comment]
Good news -- this now appears to be fixed! Someone must have complained to Xtensis. :-)
