### ISSUE TITLE
Update for Moodle 3.0

### ISSUE THREAD

**Issue by sam-moodle** [tonyjbutler/moodle-mod_nln#3]
Hi, do you plan on updating this plugin for Moodle 3.0? If so, the use of get_all_sections() in index.php needs to be replaced. It has been removed (will throw a coding_exception) as of Moodle 3.0.

https://github.com/tonyjbutler/moodle-mod_nln/blob/master/index.php#L63

**Comment by tonyjbutler** [comment]
Wow, that function has been deprecated since 2.4!

Thanks for letting me know. I don't work for an institution that actually uses this plugin anymore so I rely on people to poke me if there's an issue.

I'll get it sorted and create a new release.

**Comment by sam-moodle** [comment]
Wow to your quick response! Really appreciated. If it helps to know, I didn't find any of the other approximately 100 removed functions in the plugin.

**Comment by tonyjbutler** [comment]
Good to know, thanks.

**Comment by tonyjbutler** [comment]
New version for Moodle 3.0.x released at https://github.com/tonyjbutler/moodle-mod_nln/releases/tag/v3.0.0 (and https://moodle.org/plugins/pluginversion.php?id=10982 in the Moodle plugin repository).
